/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.product.gradle;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Product x = new Product();
        x.setName("Apple");
        x.setDesc("This ia an entry for 1 dozen red apples");
        x.setPrice(300);
        System.out.println("Name: " + x.getName() + "\nDescription: " + x.getDesc() + ".\nPrice: " + x.getPrice() + "/-");
    }
}
